default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: db/fenbahcem_development_iki

test:
  <<: *default
  database: db/fenbahcem_test

production:
  <<: *default
  database: db/fenbahcem_production
  username: fenbahcem
  password: <%= ENV['FENBAHCEM_DATABASE_PASSWORD'] %>
